# Generated by Django 3.2.8 on 2021-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='comment',
            name='neg_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='pos_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='neg_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='pos_marks',
            field=models.IntegerField(default=0),
        ),
    ]
